name: Scheduled Python Code Deployment

on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4' # Replace 'x' with your desired Python version

      - name: Install dependencies
        run: pip install -r Assets/Scripts/requirements.txt

      - name: Run Python script
        env:
          ACCESS_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }} # Referencing the secret
        run: python Assets/Scripts/crwl.py
